### ISSUE TITLE
Queries with optional variables which are not provided are not send

### ISSUE THREAD

**Issue by manuelfink** [apollostack/apollo-angular#202]
Not sure if this is expected behaviour or a bug?

I just spend ours to realize that all variable, which are defined within a query must be set in watchQuery(query, variables) otherwise the query stuck, is never send to the graphql server and a subscription never returns an response.

Would it not make sense to submit the query with optional variables not be set?

```ts
const gqlQueryPosts = gql`
query QueryPosts($offset: Int, $limit: Int, $search: String, $order: String, $orderBy: String) {
    posts(offset: $offset, limit: $limit, search: $search, order: $order, orderBy: $orderBy) {
      id
      title
      content
    }
}

export class PostsService {

  constructor(private apollo: Angular2Apollo) {
  }
  // works
  getMyPosts(variables:any = {}): ApolloQueryObservable<any> {
      return this.apollo.watchQuery({
         query: gqlQueryMyPosts,
         variables: {
           offset: variables.offset || null,
           limit: variables.limit || null,
           search: variables.search || null,
           order: variables.order || null,
           orderBy: variables.orderBy|| null
         }
       });
   }

  // not works, but should work in my optinion
  getMyPostsWithoutAllVariables(variables: any = {}): ApolloQueryObservable<any> {
      return this.apollo.watchQuery({
         query: gqlQueryMyPosts,
         variables: {
           offset: variables.offset || null,
           limit: variables.limit || null,
         }
       });
   }

  // not worsk depending on variables having all required variables, but should work too.
  getMyPostsVariblesDirectlyPassed(variables:any = {}): ApolloQueryObservable<any> {
      return this.apollo.watchQuery({
         query: gqlQueryMyPosts,
         variables
       });
   }
}
```

**Comment by Tallyb** [comment]
So here is what happened: 
- I checked how swapi behaves and wrote that you are probably right. 
- I added a comment that there is an explicit message on console specifying the variable is missing 
- I realized that is likely that this message is coming from apollo-client and not from angular2-apollo. 
- I  have checked there and came across this: https://github.com/apollostack/apollo-client/blob/744fddd26f54fd90db632cf461498e5aee05ce93/designs/arguments.md
So - it is being handled.

**Comment by kamilkisiela** [comment]
I don't think it's related to `apollo-angular` so I'm closing it but if you think differently, just @mention me :)

**Comment by chris08002** [comment]
@manuelfink Have you found any solution for this? If I run a query with empty variables in the chrome apollo developer tools, it seems the work (not always...) but if I do the same query via angular, it doesn't.

`query allVisits($customerId: ID) {
          allVisits(
            filter: {
              customer: {
                id: $customerId
              }
            }
          ) {
            id
            customer {
              id
              firstName
              lastName
            }
          }
        }`
