### ISSUE TITLE
The redux way with ng2-redux

### ISSUE THREAD

**Issue by hlehmann** [apollostack/apollo-angular#55]
Could we implement a very similar version of the redux integration:
In the bootstrap

``` typescript
    let store = createStore(
        combineReducers(reducers),
        compose(
            applyMiddleware(apolloClient.middleware()),
            window.devToolsExtension ? window.devToolsExtension() : f => f
        )
    );

    let providers = [
        NgRedux,
        APOLLO_PROVIDERS,
        defaultApolloClient(apolloClient),
    ];

    enableProdMode();
    let ngComponentRef:ComponentRef = await bootstrap(App);
    let _ngRedux:NgRedux = ngComponentRef.injector.get(NgRedux);
    _ngRedux.provideStore(store);
```

In the component

``` typescript
@connect({
    mapStateToProps(state) {
         return {...};
    },
    mapQueryToProps() {
       return {...}
    }
})
@Component({...})
export class MyComponent {

}
```

**Comment by stubailo** [comment]
What do we need to do to implement this? Perhaps we can take some of the code from `react-apollo`?

**Comment by hlehmann** [comment]
For the bootstrap there is nothing to do.
For the component I'm not sure that we can write it that way, @Urigo any thought ?

First step should be something like that 
```typescript
@Component({...})
export class MyComponent {
    constructor(private angularApollo : Angular2Apollo) {
         angularApollo.connect({
              mapQueryToProps() {
                    return {...}
              }
         })(this)
    }
}
```
The code should be the same of react-apollo exept the link with angular life cycle.

**Comment by stubailo** [comment]
How do people use Redux with Angular usually?

**Comment by hlehmann** [comment]
it's well documented here: 
http://ngcourse.rangle.io/handout/redux/

**Comment by Urigo** [comment]
@hlehmann I would love to see an example of how to use the `connect` pattern with ng-rx.
Or also using ngRedux with `connect` to an Angular 2 Component.
I've looked a lot about it and haven't found the equivalent.

Right now, I believe that the current best practice is to create a dumb Component and a parent Component that will render it.
Like [this](https://github.com/StephenFluin/apollo-ship/blob/master/src/app/shipments/shipment-short.component.ts) is the dumb component and is wrapped by [this](https://github.com/StephenFluin/apollo-ship/blob/master/src/app/shipments/shipment-short-with-data.component.ts) `component-with-data` component.

I feel like using the `connect` pattern will be cleaner here but not sure if it's popular with Angular 2.0 and ng-rx developers.
I saw [this](https://github.com/angular-redux/ng2-redux/blob/master/docs/connect-pattern.md) with ngRedux but I'm not sure it's simpler or more clean then the example above.

Would love to hear opinions from the community to figure out the best practice solution for that

**Comment by gsans** [comment]
I would say that these are the options I've seen being used in the Angular Community:
1) original Redux; there's a RxJS 5 middleware (redux-observable)
2) 3rd party bindings: ng2-redux 
3) Observables: ngrx/store and co

Adoption is still slow so no clear winner.

**Comment by camiloazula** [comment]
https://github.com/apollostack/apollo-client/issues/593#issuecomment-255331038

**Comment by alexthewilde** [comment]
For anyone still interested in integrating the Apollo client store with an existing Redux store, here's a working [example app](https://github.com/alexthewilde/angular-redux-apollo-example) I published. 

If you inspect the store with Redux DevTools, you'll see the apollo state alongside the ng2-redux store state.

**Comment by Urigo** [comment]
now also documented thanks to @alexthewilde [PR](thank for reporting, fixed [here](https://github.com/apollostack/angular2-docs/pull/30)) - http://dev.apollodata.com/angular2/redux.html
